# Enables the star prefix when a player types in chat. This prefix contains the player's star level
# which is calculated based on how many kills and wins they have obtained in the past
enable-star-prefix: true

# Enables a setting which shows how much damage an arrow does when hitting an enemy player
enable-projectile-indicator: true

# Enables a setting which allows all players to, after grace period, track enemy players by right-clicking a compass
enable-compass-tracker: true

# Enables a setting which modifies mob changes used in this plugin: e.g. Blazes and wither skeletons spawning anywhere
# in the nether or modified mob loot tables
enable-mob-changes: true

# Enables a setting where player heads drop from players when they die. These heads can be eaten instantly for speed and regeneration.
# Player heads also heal teammates
enable-player-heads: true

# Enables a setting where golden heads can be crafted from player heads and golden ingots. These golden heads can be eaten instantly for increased speed and regeneration.
# Golden heads also heal teammates for an increased amount
enable-golden-heads: true

# Enables a setting where all golden apples heal for twice the amount than they usually do (Typically used with double health UHC)
enable-double-golden-apple-healing: true

# Configure the items of UHCChampions (Their damage and names usually.)
# For recipe, enchantments, and other things, use UHCCore's files
# Note: The name option here only changes how the plugin will recognise the item
# but not the actual item name itself. Use UHCCore's files for that. Ensure both names are the same, including the colour.
items:
  # Summons lightning on target upon attack with cooldown
  axe-of-perun:
    name: "&aAxe of Perun"
    # True damage dealt upon triggering ability
    damage: 4.0
    # Cooldown in ticks. There are 20 ticks in a second, so 100 ticks is 5 seconds.
    cooldown: 100

# Items with the names listed here will not be able to be enchanted via an anvil. Ensure colour is correct too.
# The default items listed here are set to ensure items are kept in a balanced state with their new abilities.
# However, you may change them if you wish but keep in mind using a coloured item in an anvil will always remove its colour and thus
# its ability (the plugin uses names to identify if an item is what it should be)
item-enchant-disabled:
  - "&aApprentice Helmet"
  - "&aQuick Pick"
  - "&aPhilosopher Pickaxe"
  - "&aAnduril"
  - "&aDragon Chestplate"
  - "&aArtemis Bow"
  - "&aHide Of Leviathan"
  - "&aGenesis"
  - "&aShoes of Vidar"
  - "&aSeven-League Boots"
  - "&aExodus"
  - "&aAxe of Perun"
  - "&aWarlock Pants"
  - "&aCupid's Bow"
  - "&aTerminator"
  - "&aModular Bow"
  - "&aKing's Rod"
  - "&aBarbarian Chestplate"
  - "&aExcalibur"