name: UHCChampions
version: '1.1.3-SNAPSHOT'
main: me.rexe0.uhcchampions.UHCChampions
api-version: 1.13
depend: [UhcCore]
commands:
  uhcchampionsreload:
    description: Reloads the config
    usage: /uhcchampionsreload
  viewinventory:
    description: View the inventory of a player
    usage: /viewinventory <player>
    aliases: [invsee, seeinv]