name: UHCChampions
version: '1.1-SNAPSHOT'
main: me.rexe0.uhcchampions.UHCChampions
api-version: 1.13
commands:
  uhcchampionsreload:
    description: Reloads the config
    usage: /uhcchampionsreload
